### ISSUE TITLE
구글 어널리틱스 연동

### ISSUE THREAD

**Issue by tucan9389** [motlabs/motlabs.github.io#12]
이 부분을 제가 해봐도 될까요?
예전에 앱이나 블로그에 연동해본적이 있습니다.

**Comment by jwkanggist** [comment]
헐!!! 대박이네요 고고

2018년 6월 11일 (월) 오전 5:32, tucan <notifications@github.com>님이 작성:

**Comment by tucan9389** [comment]
jwkang10@gmail.com에 관리자로 초대 보내드렸습니다. 승락해주시고 #14 PR 확인해주십시오.
