### ISSUE TITLE
macOS 10.14 모하베 베타버전에서 설치 이슈

### ISSUE THREAD

**Issue by tucan9389** [motlabs/motlabs.github.io#9]
macOS 10.14 모하베 베타버전에서 ruby 설치가 안 됩니다.

**Comment by jwkanggist** [comment]
이건 저희가 커뮤니티의 솔루션을 조금 기다려야 할것 같습니다 :-) 이슈 리포팅 감사합니다

**Comment by tucan9389** [comment]
1. Xcode 베타버전을 깔고
1. 기존의 Xcode를 지운 뒤
1. 아래 링크에서 하란대로 하고
1. 터미널 껐다 켜니까 됩니다 ㅎ
ref: [https://apple.stackexchange.com/questions/327458/install-homebrew-packages-on-macos-mojave-beta](https://apple.stackexchange.com/questions/327458/install-homebrew-packages-on-macos-mojave-beta)

**Comment by Jeongah-Shin** [comment]
#### _mac OS High Sierra 10.13.4_
Beta OS가 두려웠던 Sierra 사용자에게는 모두 잘 동작합니다! 
#### d(･∀･○)
